# Generated by Django 5.0.6 on 2024-06-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Funcionario',
        ),
    ]
