# Generated by Django 5.0.6 on 2024-06-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_rename_pessoa_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('nome_social', models.CharField(max_length=100)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('vendedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('preco_custo', models.IntegerField()),
                ('preco_venda', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('compra', models.IntegerField()),
                ('vendas', models.IntegerField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.fornecedor')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.grupo')),
                ('sub_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.subgrupo')),
            ],
        ),
    ]
