# Generated by Django 5.0.6 on 2024-06-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0006_venda_itemvenda_delete_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
