# Generated by Django 5.0.6 on 2024-06-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0007_venda_finalizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='compra',
            new_name='estoque',
        ),
    ]
